Deploy to ECS

diff --git a/.github/workflows/portfolio.yml b/.github/workflows/portfolio.yml
--- a/.github/workflows/portfolio.yml
+++ b/.github/workflows/portfolio.yml
@@ -11,12 +11,31 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Build Docker image
-        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ciportfolio .
-      - name: list images
-        run: docker images
+        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }} .
+             docker build -t ${{ secrets.DOCKER_USERNAME }}/ciportfolio .
+      - name: Docker login
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
   
-    
+      - name: Push Docker image
+        run: docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }}                
+             docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio
+
+  deploy:
+      needs: Build
+      runs-on: ubuntu-latest
+      steps:
+        - name: SSH to Linux and run container 
+          uses: appleboy/ssh-action@v1
+          with:
+            host: ${{ secrets.HOST }}
+            username: ${{ secrets.USERNAME }}
+            key: ${{ secrets.KEY }}
+            script: |
+                docker rm -f portfolio || echo "Container not found, skipping removal"
+                docker run -d -p 80:85 --name portfolio ${{ secrets.DOCKER_USERNAME }}/ciportfolio
+            
        
 
- 
-     
